In [1]:
import notebook_setup
import torch
from src.models import gdGPT, GPTConfig
from src.datasets import TinyStoriesDataset
from src.tokenizers import TinyStoriesTokenizer
from src.training import train_model

Failed to install PyTorch
Requirements installed


c:\Users\will\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
torch.manual_seed(42)

In [3]:
torch.set_printoptions(linewidth=200, precision=6, sci_mode=False)

In [4]:
test_data = torch.stack([torch.stack([torch.stack([torch.ones(5) for _ in range(4)]) for _ in range(3)]) for _ in range(2)])

In [5]:
print(test_data.shape)
print(test_data)

torch.Size([2, 3, 4, 5])
tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])


In [6]:
mul_mat = torch.stack([torch.stack([torch.stack([torch.ones(1) * i * j for i in range(4)]) for j in range(3)]) for _ in range(1)])

In [7]:
print(mul_mat.shape)
print(mul_mat)

torch.Size([1, 3, 4, 1])
tensor([[[[0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [1.],
          [2.],
          [3.]],

         [[0.],
          [2.],
          [4.],
          [6.]]]])


In [8]:
result = test_data * mul_mat

In [10]:
print(result.shape)
print(result)

torch.Size([2, 3, 4, 5])
tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.],
          [3., 3., 3., 3., 3.]],

         [[0., 0., 0., 0., 0.],
          [2., 2., 2., 2., 2.],
          [4., 4., 4., 4., 4.],
          [6., 6., 6., 6., 6.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.],
          [3., 3., 3., 3., 3.]],

         [[0., 0., 0., 0., 0.],
          [2., 2., 2., 2., 2.],
          [4., 4., 4., 4., 4.],
          [6., 6., 6., 6., 6.]]]])
